version: '3.8' 

services:

  app:
    build: . 
    container_name: go_app_service
    ports:
      - "8080:8080" 
    environment:

      MONGO_URI: mongodb://mongo:27017/mydatabase 
      PORT: 8080 
    depends_on:
      - mongo # Ensures 'mongo' service starts before 'app' service
    networks:
      - app-network 

  # Service for MongoDB
  mongo:
    image: mongo:latest 
    container_name: mongo_db_service
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
    networks:
      - app-network 

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge 