// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BookingRequest defines model for BookingRequest.
type BookingRequest struct {
	// ClassId The ID of the class booked
	ClassId *string `json:"class_id,omitempty"`

	// ClassName The name of the class booked
	ClassName *string `json:"class_name,omitempty"`

	// Date The specific date of the booking
	Date *openapi_types.Date `json:"date,omitempty"`

	// MemberName The name of the member
	MemberName *string `json:"member_name,omitempty"`
}

// ClassRequest defines model for ClassRequest.
type ClassRequest struct {
	Capacity  *int                `json:"capacity,omitempty"`
	EndDate   *openapi_types.Date `json:"end_date,omitempty"`
	Name      *string             `json:"name,omitempty"`
	StartDate *openapi_types.Date `json:"start_date,omitempty"`
}

// BookClassJSONRequestBody defines body for BookClass for application/json ContentType.
type BookClassJSONRequestBody = BookingRequest

// CreateClassJSONRequestBody defines body for CreateClass for application/json ContentType.
type CreateClassJSONRequestBody = ClassRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all bookings
	// (GET /bookings)
	GetBookings(w http.ResponseWriter, r *http.Request)
	// Book a class
	// (POST /bookings)
	BookClass(w http.ResponseWriter, r *http.Request)
	// Get all classes
	// (GET /classes)
	GetClasses(w http.ResponseWriter, r *http.Request)
	// Create a new class
	// (POST /classes)
	CreateClass(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all bookings
// (GET /bookings)
func (_ Unimplemented) GetBookings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Book a class
// (POST /bookings)
func (_ Unimplemented) BookClass(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all classes
// (GET /classes)
func (_ Unimplemented) GetClasses(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new class
// (POST /classes)
func (_ Unimplemented) CreateClass(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBookings operation middleware
func (siw *ServerInterfaceWrapper) GetBookings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBookings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// BookClass operation middleware
func (siw *ServerInterfaceWrapper) BookClass(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BookClass(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetClasses operation middleware
func (siw *ServerInterfaceWrapper) GetClasses(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClasses(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateClass operation middleware
func (siw *ServerInterfaceWrapper) CreateClass(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateClass(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/bookings", wrapper.GetBookings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/bookings", wrapper.BookClass)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/classes", wrapper.GetClasses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/classes", wrapper.CreateClass)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQW/bOgz+KwLfO7q1kxR5qG+vLVBk2GEYdhmGoWAsOlFrS5qkZA2K/PeBsp0mtdtm",
	"xQbssJtCUR/Jj/wYP0Bhams06eAhfwBfLKnGeLww5k7pxUf6tiIf2EL3WNuK+FhU6P2NkpDD9D/CQp6X",
	"Z0hycj4Z41SeT6c4gaT10lgT5PDZLFBcsgUSkBjYNs7Gk5NRdpKNIIGa6jm5zv2dWWpxZQi2CVhnLLmg",
	"yB/GfgBJvnDKBmU05PBpSWJ2JUwpwpJE9BNzY+5IQgJhYxnXB6f0glH3sxtC4ptjsZp6hlC8pUKVqhDs",
	"0sHNG24hgdK4GgPkDcIA8gErr6XZOPdhtjuLmd9SERg4tmKvu09IRouFChs+t0+VDrQgx29Jy5uu5Fcr",
	"6FLvXfiALhyL0y+BTUqXJmKrwIMJ15Upzb34/8MMEliT8w1Po9PsNOOQxpJGqyCHSTQlYDEsY8Vp25T4",
	"Y0GRE2YEmesZT/o1hYvOJwFH3hrtG7rGWdbvznvlA3emAxaOglO0Jin8qijI+3JVVZtYm1/VNbpNE0Vg",
	"Ve1eRQEYP5APJ9MJyjWNvDAytqwwOpCOb9DaShXxVXrrObFO5nz611EJOfyTPu6BtF0C6ZMNEAnnOMqR",
	"hDy4FW17NIz6NLQwezVzSWdDjM30GislhduF3GeGgQQ2WoxXaTzSix27bF2GG3Y0TypQ7V+WSV+a3e3B",
	"Fnkc7T1B/fQuGhLavir7EKTlwQ7qYF7V75GbdrCuQ4kPbEe+f0taQxutNaBzuGmmdViP7dQ8K8c3DWcn",
	"224kn1XtpSMM9Dt1e7DZj1ft0bH/SmBAArGr8s+QQn/040jskvwF495MsUCh6ftuI7MHuTU5yL88hXv8",
	"ZxZr/tpbuQpySNGqdD2C7dftjwAAAP//T55AVIsKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
